### PR TITLE
Also test on Selenium 3

### PR DESCRIPTION
**Pull request by aik099**
## Observations

Used `selenium/standalone-firefox` Docker image chooses the Firefox version like so:

* Selenium 2.53.1 = Firefox 47
* Selenium 3.141.59 = Firefox 92

Not sure why, but some of the below tests fail only on Firefox 92.

## Used build

https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049068?pr=383

## Errors

> 1) Behat\Mink\Tests\Driver\Basic\IFrameTest::testIFrame
WebDriver\Exception\InvalidArgument: data did not match any variant of untagged enum FrameId at line 3 column 1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az779-213', ip: '10.1.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1056-azure', java.version: '1.8.0_[29](https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049622?pr=383#step:8:30)2'
Driver info: driver.version: unknown

* https://github.com/minkphp/MinkSelenium2Driver/pull/382

> 2) Behat\Mink\Tests\Driver\Js\ChangeEventTest::testSetValueChangeEvent with data set "file" ('the-file', '/home/runner/work/MinkSeleniu...e1.txt', '/home/runner/work/MinkSeleniu...e2.txt')
WebDriver\Exception\InvalidArgument: File not found: /home/runner/work/MinkSelenium2Driver/MinkSelenium2Driver/vendor/mink/driver-testsuite/web-fixtures/file1.txt
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az697-197', ip: '10.1.0.44', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1056-azure', java.version: '1.8.0_292'
Driver info: driver.version: unknown

* https://github.com/minkphp/MinkSelenium2Driver/pull/385

> 3) Behat\Mink\Tests\Driver\Js\WindowTest::testWindow
WebDriver\Exception\NoSuchWindow: Unable to locate window: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'fv-az697-197', ip: '10.1.0.44', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-10[56](https://github.com/minkphp/MinkSelenium2Driver/actions/runs/8015977437/job/21897049068?pr=383#step:8:57)-azure', java.version: '1.8.0_292'
Driver info: driver.version: unknown

* https://github.com/minkphp/MinkSelenium2Driver/pull/384

## Failures:

> 1) Behat\Mink\Tests\Driver\Custom\TimeoutTest::testInvalidTimeoutSettingThrowsException
Failed asserting that exception of type "\Behat\Mink\Exception\DriverException" is thrown.

* https://github.com/minkphp/MinkSelenium2Driver/pull/380

> 2) Behat\Mink\Tests\Driver\Js\EventsTest::testRightClick
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'right clicked'
> +'single clicked'

Doesn't work in both Chrome & Firefox.

* https://github.com/minkphp/MinkSelenium2Driver/issues/381 (not a PR)

## Related issues/pull requests:

* https://github.com/minkphp/MinkSelenium2Driver/pull/354
* https://github.com/minkphp/MinkSelenium2Driver/pull/372

### CODE REVIEW

**Comment by aik099** [comment]
@stof , the PRs for fixing all failing tests on Selenium 3 were created, except the `testRightClick`. Please review them.

**Review by uuf6429 — CHANGES_REQUESTED** [review]
`${{ matrix.selenium_version }}` should also be used on line 98 like below, otherwise it will conflict with #385:
```yaml
          name: logs_php-${{ matrix.php }}_selenium-${{ matrix.selenium_version }}_firefox
```

**Comment by aik099** [comment]
> `${{ matrix.selenium_version }}` should also be used on line 98 like below, otherwise it will conflict with #385:
> 
> ```yaml
>           name: logs_php-${{ matrix.php }}_selenium-${{ matrix.selenium_version }}_firefox
> ```

Done.

**Comment by aik099** [comment]
```
1) Behat\Mink\Tests\Driver\Custom\TimeoutTest::testInvalidTimeoutSettingThrowsException
Failed asserting that exception of type "\Behat\Mink\Exception\DriverException" is thrown.
```

It's not supposed to fail but fails because Selenium 3 doesn't throw (or `php-webdriver` conceals that fact) any exception upon wrong timeout name usage.

```
2) Behat\Mink\Tests\Driver\Js\EventsTest::testRightClick
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'right clicked'
+'single clicked'

/home/runner/work/MinkSelenium2Driver/MinkSelenium2Driver/vendor/mink/driver-testsuite/tests/Js/EventsTest.php:46
```

Supposed to fail, because right-clicking in Selenium 3 isn't implemented properly because of the inability to support [Mouse Actions](https://www.selenium.dev/documentation/webdriver/actions_api/mouse/).

**Comment by aik099** [comment]
Merging, because created dedicated issues for fixing failing tests.

**Pull request merged**
