### PR TITLE
Update Selenium to the latest version

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by aik099** [comment]
OK

**Comment by stof** [comment]
I updated my commit to use 2.46, and added a second commit to remove the test failing on recent versions of Selenium and not bringing much value IMO.

**Comment by aik099** [comment]
Please do not remove that. Fact, that `CurlExec` exception is now thrown and breaks the tests is a bug introduced in `php-webdriver` library in https://github.com/instaclick/php-webdriver/pull/58 (was released as 1.4.2 version, which we might want to ignore in out `composer.json`) and the fix https://github.com/instaclick/php-webdriver/pull/67 is pending review.

**Comment by LionsAd** [comment]
1.4.3 was released with the patch reverted.

**Comment by LionsAd** [comment]
So this should be good to go in

**Pull request merged**
