### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by jeremychinquistdrunomicscom**
Our project requires that the MIT license text be added to the repository. I copied it from the https://spdx.org/licenses/MIT.html#licenseText

### CODE REVIEW

**Comment by aik099** [comment]
Can you copy/paste https://github.com/minkphp/driver-testsuite/blob/master/LICENSE file into this repo and update names/years in it? Then it would be more consistent.

**Comment by jeremychinquistdrunomicscom** [comment]
@aik099 
I did that but made one exception. I left "MIT License" at the top because it is an indication again of the license and this is used elsewhere. 
Should Konstantin also be added, or simply Pete?
Please merge if this is enough.

**Comment by aik099** [comment]
> I did that but made one exception. I left "MIT License" at the top because it is an indication again of the license and this is used elsewhere.

I've removed it just because other driver repos don't have this heading and GitHub is detecting license type already (either by it's text or `MIT` word in the `composer.json`.

> Should Konstantin also be added, or simply Pete?

I'm not sure. I've left it as is.

**Comment by aik099** [comment]
@jeremychinquistdrunomicscom , merging. Thank you.

**Comment by jeremychinquistdrunomicscom** [comment]
Wonderful, thank you.

**Pull request merged**
