### PR TITLE
Reinstate code coverage

### PR DESCRIPTION
**Pull request by alexpott**
@aik099 requested this. @stof asked me to remove it from the original MR but thinking about it we should only remove it in the MR the replaces it with psalm / phpstan

### CODE REVIEW

**Comment by andypost** [comment]
Somehow Scrutinizer is stuck reporting result back to PR

**Comment by alexpott** [comment]
I got scruntinizer config from a previous build where it worked and dumped that in a .scutinizer.yml file. My guess is that the global config or project config for this project on scutinizer's site is somehow messed up. Anyway the upshot is that it is fixed.

**Comment by aik099** [comment]
@stof , any idea why we're running "PHPUnit with Coverage" for every PHP version instead of just running PHPUnit for every PHP version and for a single version run "PHPUnit with Coverage"?

It would only make sense to me when code has lots of PHP version-specific IFs, but we don't have this in Mink.

**Comment by stof** [comment]
Closing in favor of #344

**Pull request closed without merging**
