### PR TITLE
Use real textContent

### PR DESCRIPTION
**Pull request by thomaschaaf**
getText is giving me trouble in that it is not returning text for complex xpaths. By using the same function as getHtml this fixes a lot of problems for me.

### CODE REVIEW

**Comment by aik099** [comment]
This changes breaks a lot of tests. Please adjust PR so that tests will pass.

**Comment by thomaschaaf** [comment]
This should fix everything caused by my change.

**Comment by stof** [comment]
I don't understand the reason to stop using the WebDriver API in favor of doing things manually.

**Comment by thomaschaaf** [comment]
I was having problems with getText simply not returning the correct things like here:
screenshot 2016-03-22 15 52 07
screenshot 2016-03-22 15 54 30

**Comment by stof** [comment]
And if there was a case where it was broken previously, please start by sending a PR to add more tests in the driver-testsuite in Mink, so that we ensure that this case works fine in all drivers. Your PR does not ensure that anything work fine for your use case, as there is nothing preventing regressions in the future (someone could send a PR doing the exact opposite change saying that usign WebDriver is better, the testsuite would be green, and I would likely accept it as using the WebDriver API whenever possible is indeed a better idea than writing things in JS)

**Comment by stof** [comment]
well, your screenshot is not something helping us reproduce the issue (or even understanding it)

**Comment by aik099** [comment]
@thomaschaaf , please provide:

* HTML of the page you're opening via Selenium
* PHP code you're using to find element and get it's text

**Pull request closed without merging**
